// Imports the Object ID
import { ObjectId } from "mongodb";

// Interface for Minion
export default interface Minion {
    // This will be auto generated by mongodb
    id?: string | ObjectId,
    // Name of the minion
    name: string,
    // Skills of the minion
    skills: string,
    // Personality of the minion
    personality: string,
    // Email of the minion
    email: string,
    // Phone of the minion
    phone: string,
    // Description of the minion
    description: string,
    // Image of the minion
    image: string
}