// Imports the Object ID
import { ObjectId } from "mongodb";

export default interface User {
    // This will be auto generated by mongodb
    id?: string | ObjectId,
    // Email of the user
    email: string,
    // Password of the user
    password: string,
    // Minions string array added by the user
    minions?: string[]
}